### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dylansheffer** [AccessLint/a11y-agent#1]
Hey @ckundo ! I was curious what your intended licensing is for this agent? I am working on something similar and would like to reference your code, but I do not want to look at it if the licensing won't permit its use in commercial applications. Thanks!

**Comment by ckundo** [comment]
thanks @dylansheffer , just created https://github.com/AccessLint/a11y-agent/blob/main/LICENSE

**Comment by dylansheffer** [comment]
Thank you! I appreciate it
